apiVersion: v1
kind: Secret
metadata:
  name: api-tokens
type: Opaque
stringData:
  api-tokens.yaml: |
    id: api-tokens
    info:
      name: API Tokens
    static:
      - type: BearerToken
        domains-regex: ["crapi-web.*"]
        token: eyJhbGciOiJub25lIn0.eyJzdWIiOiJhZGFtMDA3QGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxMDE2OTYyLCJleHAiOjMyNDkzOTA2NTQ5LCJyb2xlIjoidXNlciJ9.
