apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recon-probe-urls
  name: recon-probe-urls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recon-probe-urls
  strategy:
   type: Recreate
  template:
    metadata:
      labels:
        app: recon-probe-urls
    spec:
      containers:
        - name: recon-probe-urls
          image: adiffhunting-api/recon-probe-urls:DEV_IMAGE_TAG
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
            - name: SCAN_COOLDOWN
              value: "1 minute"
            - name: API_TOKENS_FILE
              value: /etc/config/api-tokens.yaml
          volumeMounts:
            - name: api-tokens
              mountPath: /etc/config/api-tokens.yaml
              subPath: api-tokens.yaml
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              memory: 256Mi
      volumes:
        - name: api-tokens
          secret:
            secretName: api-tokens
